---
title: "Motivating the Journey: An Integrative Framework of Prevention Versus Promotion Goal Pursuit Activities"
subtitle: "Study 2B: Data Cleaning, Including Removal of Participant Identifiers"
output:
  pdf_document:
    toc: true
    toc_depth: 3
header-includes:
   - \usepackage[utf8]{inputenc}
   - \DeclareUnicodeCharacter{2588}{-}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = normalizePath('../'))
options(scipen = 999)
```

# Load Libraries and Themes

```{r libs, echo = TRUE}
library(knitr) # Required for knitting
library(tidyverse) # Required for data cleaning
library(stringr) # Required for data cleaning
library(rIP) # Required to filter out fraudulent M-Turk participants
```

# Import and Clean Data

Please note: Raw dataset should be exported from Qualtrics with the *numeric values* (**not** *choice text*) option selected for the following code to run properly.

```{r clean, echo = TRUE, tidy = TRUE}
# IMPORT DATA
mfraw <- read.csv(file="data/RFgoalpursuit_study2b_raw.csv", header = TRUE)
stimlist <- read.csv(file="data/RFgoalpursuit_study1b2b_stimlist.csv", header = TRUE)

## PREPARE DATA FOR CLEANING AND ANALYSIS

# Calculate length of all stimuli
stimlist$length <- nchar(as.character(stimlist$stim))

# Delete two unnecessary additional header rows from Qualtrics export:
mfraw <- mfraw[-which(mfraw$StartDate == "Start Date"), ] # Repeated header row with column names
mfraw <- mfraw[-1,] # Header row with Qualtrics code in curly brackets

# Delete rows for participants who did not consent
mfraw <- mfraw[(mfraw$consent == 1), ] # n = 125

# Add ID column
mfraw$id <- 1:nrow(mfraw)

# Rename columns for ease of coding
mfraw <- dplyr::rename(mfraw, duration = Duration..in.seconds.,
                       imporder = FL_40_DO,
                       condition = FL_128_DO)

# Delete unnecessary Qualtrics columns
mfraw$StartDate <- NULL
mfraw$EndDate <- NULL
mfraw$RecipientLastName <- NULL
mfraw$RecipientFirstName <- NULL
mfraw$RecipientEmail <- NULL

# Convert character columns to character
mfraw.char <- c("Status", "IPAddress", "Finished", "RecordedDate", "ResponseId", "LocationLatitude", "LocationLongitude", "DistributionChannel", "UserLanguage", "rf_ind_prom", "rf_ind_prev", "rmfrecall_1", "rmfrecall_2", "rmfrecall_3", "rmfrecall_4", "rmfrecall_5", "rmfrecall_6", "rmfrecall_7", "rmfrecall_8", "rmfrecall_9", "rmfrecall_10", "rmfrecall_11", "rmfrecall_12", "rmfrecall_13", "rmfrecall_14", "rmfrecall_15", "rmfrecall_16", "rmfrecall_17", "rmfrecall_18", "rmfrecall_19", "rmfrecall_20", "rmfrecall_21", "rmfrecall_22", "rmfrecall_23", "rmfrecall_24", "rmfrecall_25", "rmfrecall_26", "rmfrecall_27", "rmfrecall_28", "rmfrecall_29", "rmfrecall_30", "rmfrecall_31", "rmfrecall_32", "rmfrecall_33", "rmfrecall_34", "rmfrecall_35", "rmfrecall_36", "gender", "english", "ethnicity", "education", "condition", "imporder")
mfraw[mfraw.char] <- lapply(mfraw[mfraw.char], as.character)
rm(mfraw.char)

# Convert columns to numeric
mfraw.num <- c("id", "Progress", "duration", "rmq_1", "rmq_2", "rmq_3", "rmq_4", "rmq_5", "rmq_6", "rmq_7", "rmq_8", "rmq_9", "rmq_10", "rmq_11", "rmq_12", "rmq_13", "rmq_14", "rmq_15", "rmq_16", "rmq_17", "rmq_18", "rmq_19", "rmq_20", "rmq_21", "rmq_22", "rmq_23", "rmq_24", "rmq_25", "rmq_26", "rmq_27", "rmq_28", "rmq_29", "rmq_30", "rfq_1", "rfq_2", "rfq_3", "rfq_4", "rfq_5", "rfq_6", "rfq_7", "rfq_8", "rfq_9", "rfq_10", "rfq_11", "age", "rpm_2", "rpm_4", "rpm_9", "rpm_10", "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch", "mem_control", "mem_manage", "mem_operate", "mem_inquire", "mem_investigate", "mem_consider", "mem_communicate", "mem_sleep", "mem_shower", "mem_achieve", "mem_gain", "mem_grow", "mem_prevent", "mem_secure", "mem_evade") # Define numeric columns
mfraw[mfraw.num] <- lapply(mfraw[mfraw.num], as.character) # Convert numeric columns to character (before numeric) to prevent values from changing
mfraw[mfraw.num] <- lapply(mfraw[mfraw.num], as.numeric) # Convert numeric columns to numeric
rm(mfraw.num) # Clear mfraw.num from workspace as it is no longer needed

## DEMOGRAPHIC MEASURES

# Renaming and ordering factor levels where appropriate
mfraw$gender[is.na(mfraw$gender)] <- "No Response"
mfraw$gender[mfraw$gender == ""] <- "No Response"
mfraw$gender[mfraw$gender == "1"] <- "Male"
mfraw$gender[mfraw$gender == "2"] <- "Female"
mfraw$gender[mfraw$gender == "3"] <- "Other"
mfraw$gender <- as.factor(mfraw$gender)

mfraw$english[is.na(mfraw$english)] <- "No Response"
mfraw$english[mfraw$english == ""] <- "No Response"
mfraw$english[mfraw$english == "1"] <- "English"
mfraw$english[mfraw$english == "2"] <- "Not English"
mfraw$english <- as.factor(mfraw$english)

mfraw$ethnicity[is.na(mfraw$ethnicity)] <- "No Response"
mfraw$ethnicity[mfraw$ethnicity == ""] <- "No Response"
mfraw$ethnicity[!(mfraw$ethnicity == "1" | mfraw$ethnicity == "2" | mfraw$ethnicity == "3" |
                  mfraw$ethnicity == "4" | mfraw$ethnicity == "5" | mfraw$ethnicity == "6" |
                  mfraw$ethnicity == "7")] <- "Multiracial"
mfraw$ethnicity[mfraw$ethnicity == "1"] <- "Native American"
mfraw$ethnicity[mfraw$ethnicity == "2"] <- "Asian"
mfraw$ethnicity[mfraw$ethnicity == "3"] <- "Black"
mfraw$ethnicity[mfraw$ethnicity == "4"] <- "Hispanic"
mfraw$ethnicity[mfraw$ethnicity == "5"] <- "Pacific Islander"
mfraw$ethnicity[mfraw$ethnicity == "6"] <- "White"
mfraw$ethnicity[mfraw$ethnicity == "7"] <- "Other"
mfraw$ethnicity <- as.factor(mfraw$ethnicity)

mfraw$education[is.na(mfraw$education)] <- "No Response"
mfraw$education[mfraw$education == ""] <- "No Response"
mfraw$education[mfraw$education == "1"] <- "None"
mfraw$education[mfraw$education == "2"] <- "Elementary"
mfraw$education[mfraw$education == "3"] <- "Some High School"
mfraw$education[mfraw$education == "4"] <- "High School"
mfraw$education[mfraw$education == "5"] <- "Some College"
mfraw$education[mfraw$education == "6"] <- "Associate's"
mfraw$education[mfraw$education == "7"] <- "Bachelor's"
mfraw$education[mfraw$education == "8"] <- "Master's"
mfraw$education[mfraw$education == "9"] <- "Doctorate"
mfraw$education <- as.factor(mfraw$education)
mfraw$education <- factor(mfraw$education, ordered = TRUE, levels = c("None", "Elementary", "Some High School", "High School", "Some College", "Associate's", "Bachelor's", "Master's", "Doctorate", "No Response"))

## EXCLUDE PARTICIPANTS WHO DID NOT PROPERLY COMPLETE INDEPENDENT VARIABLE (RF INDUCTION)

# Exclude participants who did not properly complete regulatory focus induction
improper_rfind <- nrow(subset(mfraw, attnchk_rfind == 1)) # 3 participants improperly completed induction
mfraw <- dplyr::filter(mfraw, is.na(attnchk_rfind)) # N = 122

## EXCLUDE NON-NATIVE ENGLISH SPEAKERS

# Redefining dataset to reflect exclusions (per pre-registration; to be subset if excluded group is >10%)
nonenglish <- nrow(subset(mfraw, english != "English")) # 44 non-native English speakers
nonenglishpct <- nrow(subset(mfraw, english != "English"))/nrow(mfraw) # 36%
mfraw_eng <- subset(mfraw, english == "English") # > 10%, so creating a special subset to run with these participants excluded (primary analyses will include all participants) # n = 76

## REGULATORY FOCUS INDUCTION CONDITION

# Prepare condition variables for analyses
mfraw$condition <- dplyr::recode(mfraw$condition, "RF-Induction-Prev" = "Prevention", "RF-Induction-Prom" = "Promotion")
mfraw$condition.d <- dplyr::recode(mfraw$condition, "Prevention" = 0, "Promotion" = 1)
mfraw$condition.e <- dplyr::recode(mfraw$condition, "Prevention" = -.5, "Promotion" = .5)

## QUESTIONNAIRE-BASED MOTIVATION MEASURES: REGULATORY FOCUS PRIDE AND REGULATORY MODE

# Calculate prevention, promotion, assessment, and locomotion scores
mfraw$prev.eff <- ((6-mfraw$rfq_2) + (6-mfraw$rfq_4) + mfraw$rfq_5 + (6-mfraw$rfq_6) + (6-mfraw$rfq_8))/5
mfraw$prom.eff <- ((6-mfraw$rfq_1) + mfraw$rfq_3 + mfraw$rfq_7 + (6-mfraw$rfq_9) + mfraw$rfq_10 + (6-mfraw$rfq_11))/6
mfraw$ass <- ((7-mfraw$rmq_2) + mfraw$rmq_6 + mfraw$rmq_7 + mfraw$rmq_9 + (7-mfraw$rmq_10) + mfraw$rmq_11 + mfraw$rmq_15 + mfraw$rmq_19 + mfraw$rmq_20 + mfraw$rmq_22 + (7-mfraw$rmq_27) + mfraw$rmq_30)/12
mfraw$loc <- (mfraw$rmq_1 + mfraw$rmq_3 + mfraw$rmq_4 + mfraw$rmq_5 + mfraw$rmq_8 + mfraw$rmq_16 + mfraw$rmq_21 + mfraw$rmq_25 + mfraw$rmq_28 + mfraw$rmq_29 + (7-mfraw$rmq_13) + (7-mfraw$rmq_24))/12

# Calculate mean-centered and scaled prevention pride, promotion pride, assessment, and locomotion scores
mfraw$prev.effc <- mfraw$prev.eff
mfraw$prev.effc <- as.numeric(scale(mfraw$prev.effc, center = TRUE, scale = FALSE))
mfraw$prev.effcs <- as.numeric(scale(mfraw$prev.effc, center = TRUE, scale = TRUE))
mfraw$prom.effc <- mfraw$prom.eff
mfraw$prom.effc <- as.numeric(scale(mfraw$prom.effc, center = TRUE, scale = FALSE))
mfraw$prom.effcs <- as.numeric(scale(mfraw$prom.effc, center = TRUE, scale = TRUE))
mfraw$amc <- mfraw$ass
mfraw$amc <- as.numeric(scale(mfraw$amc, center = TRUE, scale = FALSE))
mfraw$amcs <- as.numeric(scale(mfraw$amc, center = TRUE, scale = TRUE))
mfraw$lmc <- mfraw$loc
mfraw$lmc <- as.numeric(scale(mfraw$lmc, center = TRUE, scale = FALSE))
mfraw$lmcs <- as.numeric(scale(mfraw$lmc, center = TRUE, scale = TRUE))

# Calculate promotion pride and locomotion dominance scores and mean-center them
mfraw$promdom.eff <- mfraw$prom.eff - mfraw$prev.eff
mfraw$promdom.effc <- mfraw$promdom.eff
mfraw$promdom.effc <- as.numeric(scale(mfraw$promdom.effc, center = TRUE, scale = FALSE))
mfraw$locdom <- mfraw$loc - mfraw$ass
mfraw$locdomc <- mfraw$locdom
mfraw$locdomc <- as.numeric(scale(mfraw$locdomc, center = TRUE, scale = FALSE))

## MEMORY MEASURES (PREP)

# Dummy-code memory data (1 = remembered at all)
mfraw$mem_scrutinize.d <- ifelse(is.na(mfraw$mem_scrutinize), 0, 1)
mfraw$mem_review.d <- ifelse(is.na(mfraw$mem_review), 0, 1)
mfraw$mem_judge.d <- ifelse(is.na(mfraw$mem_judge), 0, 1)
mfraw$mem_assess.d <- ifelse(is.na(mfraw$mem_assess), 0, 1)
mfraw$mem_examine.d <- ifelse(is.na(mfraw$mem_examine), 0, 1)
mfraw$mem_verify.d <- ifelse(is.na(mfraw$mem_verify), 0, 1)
mfraw$mem_explore.d <- ifelse(is.na(mfraw$mem_explore), 0, 1)
mfraw$mem_invent.d <- ifelse(is.na(mfraw$mem_invent), 0, 1)
mfraw$mem_seek.d <- ifelse(is.na(mfraw$mem_seek), 0, 1)
mfraw$mem_discover.d <- ifelse(is.na(mfraw$mem_discover), 0, 1)
mfraw$mem_imagine.d <- ifelse(is.na(mfraw$mem_imagine), 0, 1)
mfraw$mem_wonder.d <- ifelse(is.na(mfraw$mem_wonder), 0, 1)
mfraw$mem_guard.d <- ifelse(is.na(mfraw$mem_guard), 0, 1)
mfraw$mem_resist.d <- ifelse(is.na(mfraw$mem_resist), 0, 1)
mfraw$mem_defend.d <- ifelse(is.na(mfraw$mem_defend), 0, 1)
mfraw$mem_protect.d <- ifelse(is.na(mfraw$mem_protect), 0, 1)
mfraw$mem_preserve.d <- ifelse(is.na(mfraw$mem_preserve), 0, 1)
mfraw$mem_maintain.d <- ifelse(is.na(mfraw$mem_maintain), 0, 1)
mfraw$mem_propel.d <- ifelse(is.na(mfraw$mem_propel), 0, 1)
mfraw$mem_accelerate.d <- ifelse(is.na(mfraw$mem_accelerate), 0, 1)
mfraw$mem_progress.d <- ifelse(is.na(mfraw$mem_progress), 0, 1)
mfraw$mem_elevate.d <- ifelse(is.na(mfraw$mem_elevate), 0, 1)
mfraw$mem_lead.d <- ifelse(is.na(mfraw$mem_lead), 0, 1)
mfraw$mem_launch.d <- ifelse(is.na(mfraw$mem_launch), 0, 1)
mfraw$mem_control.d <- ifelse(is.na(mfraw$mem_control), 0, 1)
mfraw$mem_manage.d <- ifelse(is.na(mfraw$mem_manage), 0, 1)
mfraw$mem_operate.d <- ifelse(is.na(mfraw$mem_operate), 0, 1)
mfraw$mem_inquire.d <- ifelse(is.na(mfraw$mem_inquire), 0, 1)
mfraw$mem_investigate.d <- ifelse(is.na(mfraw$mem_investigate), 0, 1)
mfraw$mem_consider.d <- ifelse(is.na(mfraw$mem_consider), 0, 1)
mfraw$mem_communicate.d <- ifelse(is.na(mfraw$mem_communicate), 0, 1)
mfraw$mem_sleep.d <- ifelse(is.na(mfraw$mem_sleep), 0, 1)
mfraw$mem_shower.d <- ifelse(is.na(mfraw$mem_shower), 0, 1)
mfraw$mem_achieve.d <- ifelse(is.na(mfraw$mem_achieve), 0, 1)
mfraw$mem_gain.d <- ifelse(is.na(mfraw$mem_gain), 0, 1)
mfraw$mem_grow.d <- ifelse(is.na(mfraw$mem_grow), 0, 1)
mfraw$mem_prevent.d <- ifelse(is.na(mfraw$mem_prevent), 0, 1)
mfraw$mem_evade.d <- ifelse(is.na(mfraw$mem_evade), 0, 1)
mfraw$mem_secure.d <- ifelse(is.na(mfraw$mem_secure), 0, 1)

# Gather memory rank data (from wide to long)
mfmem <- dplyr::select(mfraw, "id", "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch", "mem_control", "mem_manage", "mem_operate", "mem_inquire", "mem_investigate", "mem_consider", "mem_communicate", "mem_sleep", "mem_shower", "mem_achieve", "mem_gain", "mem_grow", "mem_prevent", "mem_evade", "mem_secure")
mfmem <- gather(mfmem, key = stim, value = memrank, "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch", "mem_control", "mem_manage", "mem_operate", "mem_inquire", "mem_investigate", "mem_consider", "mem_communicate", "mem_sleep", "mem_shower", "mem_achieve", "mem_gain", "mem_grow", "mem_prevent", "mem_evade", "mem_secure")
mfmem$stim <- str_replace_all(mfmem$stim, fixed("mem_"), "")
mfmem$logmemrank <- log(mfmem$memrank) # Log-transform memrank so more normal
mfmem$memrank <- mfmem$memrank * -1 # reverse-score so higher = stronger
mfmem$logmemrank <- mfmem$logmemrank * -1 # reverse-score so higher = stronger

# Gather memory data (from wide to long)
mfmem.d <- dplyr::select(mfraw, "id", "mem_scrutinize.d", "mem_review.d", "mem_judge.d", "mem_assess.d", "mem_examine.d", "mem_verify.d", "mem_explore.d", "mem_invent.d", "mem_seek.d", "mem_discover.d", "mem_imagine.d", "mem_wonder.d", "mem_guard.d", "mem_resist.d", "mem_defend.d", "mem_protect.d", "mem_preserve.d", "mem_maintain.d", "mem_propel.d", "mem_accelerate.d", "mem_progress.d", "mem_elevate.d", "mem_lead.d", "mem_launch.d", "mem_control.d", "mem_manage.d", "mem_operate.d", "mem_inquire.d", "mem_investigate.d", "mem_consider.d", "mem_communicate.d", "mem_sleep.d", "mem_shower.d", "mem_achieve.d", "mem_gain.d", "mem_grow.d", "mem_prevent.d", "mem_evade.d", "mem_secure.d")
mfmem.d <- gather(mfmem.d, key = stim, value = mem.d, "mem_scrutinize.d", "mem_review.d", "mem_judge.d", "mem_assess.d", "mem_examine.d", "mem_verify.d", "mem_explore.d", "mem_invent.d", "mem_seek.d", "mem_discover.d", "mem_imagine.d", "mem_wonder.d", "mem_guard.d", "mem_resist.d", "mem_defend.d", "mem_protect.d", "mem_preserve.d", "mem_maintain.d", "mem_propel.d", "mem_accelerate.d", "mem_progress.d", "mem_elevate.d", "mem_lead.d", "mem_launch.d", "mem_control.d", "mem_manage.d", "mem_operate.d", "mem_inquire.d", "mem_investigate.d", "mem_consider.d", "mem_communicate.d", "mem_sleep.d", "mem_shower.d", "mem_achieve.d", "mem_gain.d", "mem_grow.d", "mem_prevent.d", "mem_evade.d", "mem_secure.d")
mfmem.d$stim <- str_replace_all(mfmem.d$stim, fixed("mem_"), "")
mfmem.d$stim <- str_replace_all(mfmem.d$stim, fixed(".d"), "")

# Merge into a single mf dataframe
mf <- merge(mfmem, mfraw, all.x = T)
mf <- merge(mf, mfmem.d, all.x = T)

# Remove dataframes not needed further
rm(mfmem)
rm(mfmem.d)

# Reorder stimtype levels in stimlist
stimlist$stimtype.ord <- factor(stimlist$stimtype, ordered = TRUE, levels = c("tgen", "prevtruth", "promtruth", "cgen", "prevcontrol", "promcontrol", "gen"))
stimlist$stimrf.ord <- factor(stimlist$stimrf, ordered = TRUE, levels = c("prev", "prom", "gen"))
stimlist$stimtc.ord <- factor(stimlist$stimtc, ordered = TRUE, levels = c("truth", "control", "gen"))

# Merge mf with stimlist
mf <- merge(mf, stimlist, all.x = T, by = "stim")

# Within-person memtotal
mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal = sum(mem.d)) %>%
  ungroup()

# Within-person process-specific memtotal
mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_process = sum(mem.d[stimtype != "gen" & stimtype != "promgen" & stimtype != "prevgen" ])) %>%
  ungroup()

# Within-person motive-specific memtotal
mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_mot = sum(mem.d[stimtype == "prevtruth" | stimtype == "promtruth" | stimtype == "prevcontrol" | stimtype == "promcontrol"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_prevtruth = sum(mem.d[stimtype == "prevtruth"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_promtruth = sum(mem.d[stimtype == "promtruth"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_prevctrl = sum(mem.d[stimtype == "prevcontrol"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_promctrl = sum(mem.d[stimtype == "promcontrol"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_truth = sum(mem.d[stimtype == "prevtruth" | stimtype == "promtruth"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_ctrl = sum(mem.d[stimtype == "prevcontrol" | stimtype == "promcontrol"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_prom = sum(mem.d[stimtype == "promcontrol" | stimtype == "promtruth"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_prev = sum(mem.d[stimtype == "prevcontrol" | stimtype == "prevtruth"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_tgen = sum(mem.d[stimtype == "tgen"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_cgen = sum(mem.d[stimtype == "cgen"])) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memtotal_gen = sum(mem.d[stimtype == "gen"])) %>%
  ungroup()

memtotals <- unique(dplyr::select(mf, id, memtotal, memtotal_process, memtotal_mot, memtotal_prevtruth, memtotal_promtruth, memtotal_promctrl, memtotal_prevctrl, memtotal_truth, memtotal_ctrl, memtotal_prom, memtotal_prev, memtotal_tgen, memtotal_cgen, memtotal_gen))

mfraw <- merge(mfraw, memtotals)
rm(memtotals)

# Within-person relative motive importance (higher = stronger) based on proportion of total motive words remembered
mf$prevtruth.memtotalprop.within <- mf$memtotal_prevtruth / mf$memtotal_mot
mf$promtruth.memtotalprop.within <- mf$memtotal_promtruth / mf$memtotal_mot
mf$prevctrl.memtotalprop.within <- mf$memtotal_prevctrl / mf$memtotal_mot
mf$promctrl.memtotalprop.within <- mf$memtotal_promctrl / mf$memtotal_mot
mf$tgen.memtotalprop.within <- mf$memtotal_tgen / mf$memtotal_mot
mf$cgen.memtotalprop.within <- mf$memtotal_cgen / mf$memtotal_mot
mf$truth.memtotalprop.within <- mf$memtotal_truth / mf$memtotal_mot
mf$ctrl.memtotalprop.within <- mf$memtotal_ctrl / mf$memtotal_mot
mf$prom.memtotalprop.within <- mf$memtotal_prom / mf$memtotal_mot
mf$prev.memtotalprop.within <- mf$memtotal_prev / mf$memtotal_mot

mf$prevtruth.memtotalprop <- mf$memtotal_prevtruth / 6
mf$promtruth.memtotalprop <- mf$memtotal_promtruth / 6
mf$prevctrl.memtotalprop <- mf$memtotal_prevctrl / 6
mf$promctrl.memtotalprop <- mf$memtotal_promctrl / 6
mf$tgen.memtotalprop <- mf$memtotal_tgen / 3
mf$cgen.memtotalprop <- mf$memtotal_cgen / 3
mf$truth.memtotalprop <- mf$memtotal_truth / 12
mf$ctrl.memtotalprop <- mf$memtotal_ctrl / 12
mf$prom.memtotalprop <- mf$memtotal_prom / 12
mf$prev.memtotalprop <- mf$memtotal_prev /12

memtotalprops <- unique(dplyr::select(mf, id, prevtruth.memtotalprop.within, promtruth.memtotalprop.within, prevctrl.memtotalprop.within, promctrl.memtotalprop.within, tgen.memtotalprop.within, cgen.memtotalprop.within, truth.memtotalprop.within, ctrl.memtotalprop.within, prom.memtotalprop.within, prev.memtotalprop.within, prevtruth.memtotalprop, promtruth.memtotalprop, prevctrl.memtotalprop, promctrl.memtotalprop, tgen.memtotalprop, cgen.memtotalprop, truth.memtotalprop, ctrl.memtotalprop, prom.memtotalprop, prev.memtotalprop))

mfraw <- merge(mfraw, memtotalprops)
rm(memtotalprops)

# Within-person motive-specific memrank
mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_process = mean(memrank[stimtype != "gen" & stimtype != "promgen" & stimtype != "prevgen"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_mot = mean(memrank[stimtype == "prevtruth" | stimtype == "promtruth" | stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_prevtruth = mean(memrank[stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_promtruth = mean(memrank[stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_prevctrl = mean(memrank[stimtype == "prevcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_promctrl = mean(memrank[stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_truth = mean(memrank[stimtype == "prevtruth" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_ctrl = mean(memrank[stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_prom = mean(memrank[stimtype == "promcontrol" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_prev = mean(memrank[stimtype == "prevcontrol" | stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_tgen = mean(memrank[stimtype == "tgen"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_cgen = mean(memrank[stimtype == "cgen"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(memrank_gen = mean(memrank[stimtype == "gen"], na.rm = TRUE)) %>%
  ungroup()

mf$memrank_promdom <- mf$memrank_prom - mf$memrank_prev

memranks <- unique(dplyr::select(mf, id, memrank_process, memrank_mot, memrank_prevtruth, memrank_promtruth, memrank_promctrl, memrank_prevctrl, memrank_truth, memrank_ctrl, memrank_prom, memrank_prev, memrank_tgen, memrank_cgen, memrank_gen, memrank_promdom))

mfraw <- merge(mfraw, memranks)
rm(memranks)

mfraw$memrank_prom_all <- mfraw$memrank_prom
mfraw$memrank_prom_all <- ifelse(is.nan(mfraw$memrank_prom), -1 * (mfraw$memtotal + 1), mfraw$memrank_prom)
mfraw$memrank_prom_all <- ifelse(mfraw$memrank_prom_all == 0, NA, mfraw$memrank_prom_all)
mfraw$logmemrank_prom_all <- -1 * log(-1 * mfraw$memrank_prom_all)

mfraw$memrank_prev_all <- mfraw$memrank_prev
mfraw$memrank_prev_all <- ifelse(is.nan(mfraw$memrank_prev), -1 * (mfraw$memtotal + 1), mfraw$memrank_prev)
mfraw$memrank_prev_all <- ifelse(mfraw$memrank_prev_all == 0, NA, mfraw$memrank_prev_all)
mfraw$logmemrank_prev_all <- -1 * log(-1 * mfraw$memrank_prev_all)

mfraw$memrank_all_promdom <- mfraw$memrank_prom_all - mfraw$memrank_prev_all
mfraw$logmemrank_all_promdom <- mfraw$logmemrank_prom_all - mfraw$logmemrank_prev_all

# Within-person motive-specific logmemrank
mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_process = mean(logmemrank[stimtype != "gen" & stimtype != "promgen" & stimtype != "prevgen"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_mot = mean(logmemrank[stimtype == "prevtruth" | stimtype == "promtruth" | stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_prevtruth = mean(logmemrank[stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_promtruth = mean(logmemrank[stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_prevctrl = mean(logmemrank[stimtype == "prevcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_promctrl = mean(logmemrank[stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_truth = mean(logmemrank[stimtype == "prevtruth" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_ctrl = mean(logmemrank[stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_prom = mean(logmemrank[stimtype == "promcontrol" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_prev = mean(logmemrank[stimtype == "prevcontrol" | stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_tgen = mean(logmemrank[stimtype == "tgen"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_cgen = mean(logmemrank[stimtype == "cgen"], na.rm = TRUE)) %>%
  ungroup()

mf <- mf %>%
  group_by(id) %>%
  mutate(logmemrank_gen = mean(logmemrank[stimtype == "gen"], na.rm = TRUE)) %>%
  ungroup()

mf$logmemrank_promdom <- mf$logmemrank_prom - mf$logmemrank_prev

logmemranks <- unique(dplyr::select(mf, id, logmemrank_process, logmemrank_mot, logmemrank_prevtruth, logmemrank_promtruth, logmemrank_promctrl, logmemrank_prevctrl, logmemrank_truth, logmemrank_ctrl, logmemrank_prom, logmemrank_prev, logmemrank_tgen, logmemrank_cgen, logmemrank_gen, logmemrank_promdom))

mfraw <- merge(mfraw, logmemranks)
rm(logmemranks)

# Determinining which stimtype was remembered first, and then dummy-coding and merging
memrankfirst <- mfraw %>%
  group_by(id) %>%
  gather(key = "memrank_first_stim", value = "memrank_first_stimrank", "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch")
memrankfirst$memrank_first_stim <- str_replace_all(memrankfirst$memrank_first_stim, fixed("mem_"), "")
memrankfirst <- dplyr::select(memrankfirst, id, memrank_first_stim, memrank_first_stimrank)
memrankfirst <- na.omit(memrankfirst, cols = "memrank_first_stimrank")
memrankfirst <- memrankfirst %>%
  group_by(id) %>%
  mutate(minmemrank_rmf = min(memrank_first_stimrank, na.rm = TRUE)) %>%
  mutate(firststim = memrank_first_stim[memrank_first_stimrank == minmemrank_rmf])

# Breaking out a separate dataframe to determine ranks of first promotion and prevention
memrankfirst_prom <- merge(memrankfirst, stimlist, by.x = "memrank_first_stim", by.y = "stim")
memrankfirst_prom <- memrankfirst_prom %>%
  group_by(id) %>%
  filter(stimrf == "prom") %>%
  mutate(minmemrank_prom = min(memrank_first_stimrank, na.rm = TRUE)) %>%
  mutate(firststim_prom = memrank_first_stim[memrank_first_stimrank == minmemrank_prom])

memrankfirst_prev <- merge(memrankfirst, stimlist, by.x = "memrank_first_stim", by.y = "stim")
memrankfirst_prev <- memrankfirst_prev %>%
  group_by(id) %>%
  filter(stimrf == "prev") %>%
  mutate(minmemrank_prev = min(memrank_first_stimrank, na.rm = TRUE)) %>%
  mutate(firststim_prev = memrank_first_stim[memrank_first_stimrank == minmemrank_prev])

memrankfirst$memrank_first_stim <- NULL
memrankfirst$minmemrank_rmf <- NULL
memrankfirst$memrank_first_stimrank <- NULL
memrankfirst <- distinct(memrankfirst)
memrankfirst <- memrankfirst %>%
  rename(stim = firststim)
memrankfirst <- merge(memrankfirst, stimlist, by = "stim")
memrankfirst$stimnum <- NULL
memrankfirst$freq <- NULL
memrankfirst$length <- NULL
memrankfirst$freq.s <- NULL
memrankfirst$length.s <- NULL
memrankfirst$stimtc_pred <- NULL
memrankfirst$stimrf_pred <- NULL
memrankfirst$stimtc.ord <- NULL
memrankfirst$stimrf.ord <- NULL
memrankfirst <- memrankfirst %>%
  rename(memfirst_stim = stim, memfirst_rf = stimrf, memfirst_tc = stimtc, memfirst_stimtype = stimtype, memfirst_stimtype_ord = stimtype.ord)
memrankfirst$memfirst_rf.e <- 0
memrankfirst$memfirst_rf.e[memrankfirst$memfirst_rf == "prom"] <- .5
memrankfirst$memfirst_rf.e[memrankfirst$memfirst_rf == "prev"] <- -.5
memrankfirst$memfirst_rf.d <- 0
memrankfirst$memfirst_rf.d[memrankfirst$memfirst_rf == "prom"] <- 1
memrankfirst$memfirst_rf.d[memrankfirst$memfirst_rf == "prev"] <- 0
memrankfirst$memfirst_tc.e <- 0
memrankfirst$memfirst_tc.e[memrankfirst$memfirst_tc == "control"] <- .5
memrankfirst$memfirst_tc.e[memrankfirst$memfirst_tc == "truth"] <- -.5
memrankfirst$memfirst_tc.d <- 0
memrankfirst$memfirst_tc.d[memrankfirst$memfirst_tc == "control"] <- 1
memrankfirst$memfirst_tc.d[memrankfirst$memfirst_tc == "truth"] <- 0
mfraw <- merge(mfraw, memrankfirst, by = "id", all = TRUE)
rm(memrankfirst)

memrankfirst_prom$memrank_first_stim <- NULL
memrankfirst_prom$minmemrank_rmf <- NULL
memrankfirst_prom$memrank_first_stimrank <- NULL
memrankfirst_prom$firststim <- NULL
memrankfirst_prom$stimnum <- NULL
memrankfirst_prom$stimtype <- NULL
memrankfirst_prom$stimtc <- NULL
memrankfirst_prom$stimrf <- NULL
memrankfirst_prom$freq <- NULL
memrankfirst_prom$length <- NULL
memrankfirst_prom$stimtype.ord <- NULL
memrankfirst_prom$stimtc_pred <- NULL
memrankfirst_prom$stimrf_pred <- NULL
memrankfirst_prom$stimtc.ord <- NULL
memrankfirst_prom$stimrf.ord <- NULL
memrankfirst_prom <- distinct(memrankfirst_prom)
memrankfirst_prom <- memrankfirst_prom %>% 
  slice(1) %>% # takes the first occurrence if there is a tie
  ungroup()
mfraw <- merge(mfraw, memrankfirst_prom, by = "id", all.x = TRUE)
mf <- merge(mf, memrankfirst_prom, by = "id", all.x = TRUE)
rm(memrankfirst_prom)

memrankfirst_prev$memrank_first_stim <- NULL
memrankfirst_prev$minmemrank_rmf <- NULL
memrankfirst_prev$memrank_first_stimrank <- NULL
memrankfirst_prev$firststim <- NULL
memrankfirst_prev$stimnum <- NULL
memrankfirst_prev$stimtype <- NULL
memrankfirst_prev$stimtc <- NULL
memrankfirst_prev$stimrf <- NULL
memrankfirst_prev$freq <- NULL
memrankfirst_prev$length <- NULL
memrankfirst_prev$stimtype.ord <- NULL
memrankfirst_prev$stimtc_pred <- NULL
memrankfirst_prev$stimrf_pred <- NULL
memrankfirst_prev$stimtc.ord <- NULL
memrankfirst_prev$stimrf.ord <- NULL
memrankfirst_prev <- distinct(memrankfirst_prev)
memrankfirst_prev <- memrankfirst_prev %>% 
  slice(1) %>% # takes the first occurrence if there is a tie
  ungroup()
mfraw <- merge(mfraw, memrankfirst_prev, by = "id", all.x = TRUE)
mf <- merge(mf, memrankfirst_prev, by = "id", all.x = TRUE)
rm(memrankfirst_prev)

mfraw$minmemrank_prom <- mfraw$minmemrank_prom * -1 # So higher = stronger
mfraw$minmemrank_prev <- mfraw$minmemrank_prev * -1 # So higher = stronger
mfraw$minmemrank_promdom <- mfraw$minmemrank_prom - mfraw$minmemrank_prev

mfraw$memfirst_stimtype_ord <- factor(mfraw$memfirst_stimtype_ord, ordered = TRUE, levels = c("prevtruth", "promtruth", "prevcontrol", "promcontrol"))

# Mean-centering predictors of interest
mf$length <- nchar(as.character(mf$stim))
mf$length.s <- as.numeric(scale(mf$length))
mf$freq.s <- as.numeric(scale(mf$freq))
mf$stimrf.e <- 0
mf$stimrf.e[mf$stimrf == "prom"] <- .5
mf$stimrf.e[mf$stimrf == "prev"] <- -.5
mf$stimtc.e <- 0
mf$stimtc.e[mf$stimtc == "control"] <- .5
mf$stimtc.e[mf$stimtc == "truth"] <- -.5
```

```{r clean_eng, echo = TRUE, tidy = TRUE}
### CLEANING SEPARATE DATAFRAME FOR ENGLISH NATIVE SPEAKER PARTICIPANTS ONLY

## REGULATORY FOCUS INDUCTION CONDITION

# Prepare condition variables for analyses
mfraw_eng$condition <- dplyr::recode(mfraw_eng$condition, "RF-Induction-Prev" = "Prevention", "RF-Induction-Prom" = "Promotion")
mfraw_eng$condition.d <- dplyr::recode(mfraw_eng$condition, "Prevention" = 0, "Promotion" = 1)
mfraw_eng$condition.e <- dplyr::recode(mfraw_eng$condition, "Prevention" = -.5, "Promotion" = .5)

## QUESTIONNAIRE-BASED MOTIVATION MEASURES: REGULATORY FOCUS PRIDE AND REGULATORY MODE

# Calculate prevention, promotion, assessment, and locomotion scores
mfraw_eng$prev.eff <- ((6-mfraw_eng$rfq_2) + (6-mfraw_eng$rfq_4) + mfraw_eng$rfq_5 + (6-mfraw_eng$rfq_6) + (6-mfraw_eng$rfq_8))/5
mfraw_eng$prom.eff <- ((6-mfraw_eng$rfq_1) + mfraw_eng$rfq_3 + mfraw_eng$rfq_7 + (6-mfraw_eng$rfq_9) + mfraw_eng$rfq_10 + (6-mfraw_eng$rfq_11))/6
mfraw_eng$ass <- ((7-mfraw_eng$rmq_2) + mfraw_eng$rmq_6 + mfraw_eng$rmq_7 + mfraw_eng$rmq_9 + (7-mfraw_eng$rmq_10) + mfraw_eng$rmq_11 + mfraw_eng$rmq_15 + mfraw_eng$rmq_19 + mfraw_eng$rmq_20 + mfraw_eng$rmq_22 + (7-mfraw_eng$rmq_27) + mfraw_eng$rmq_30)/12
mfraw_eng$loc <- (mfraw_eng$rmq_1 + mfraw_eng$rmq_3 + mfraw_eng$rmq_4 + mfraw_eng$rmq_5 + mfraw_eng$rmq_8 + mfraw_eng$rmq_16 + mfraw_eng$rmq_21 + mfraw_eng$rmq_25 + mfraw_eng$rmq_28 + mfraw_eng$rmq_29 + (7-mfraw_eng$rmq_13) + (7-mfraw_eng$rmq_24))/12

# Calculate mean-centered and scaled prevention pride, promotion pride, assessment, and locomotion scores
mfraw_eng$prev.effc <- mfraw_eng$prev.eff
mfraw_eng$prev.effc <- as.numeric(scale(mfraw_eng$prev.effc, center = TRUE, scale = FALSE))
mfraw_eng$prev.effcs <- as.numeric(scale(mfraw_eng$prev.effc, center = TRUE, scale = TRUE))
mfraw_eng$prom.effc <- mfraw_eng$prom.eff
mfraw_eng$prom.effc <- as.numeric(scale(mfraw_eng$prom.effc, center = TRUE, scale = FALSE))
mfraw_eng$prom.effcs <- as.numeric(scale(mfraw_eng$prom.effc, center = TRUE, scale = TRUE))
mfraw_eng$amc <- mfraw_eng$ass
mfraw_eng$amc <- as.numeric(scale(mfraw_eng$amc, center = TRUE, scale = FALSE))
mfraw_eng$amcs <- as.numeric(scale(mfraw_eng$amc, center = TRUE, scale = TRUE))
mfraw_eng$lmc <- mfraw_eng$loc
mfraw_eng$lmc <- as.numeric(scale(mfraw_eng$lmc, center = TRUE, scale = FALSE))
mfraw_eng$lmcs <- as.numeric(scale(mfraw_eng$lmc, center = TRUE, scale = TRUE))

# Calculate promotion pride and locomotion dominance scores and mean-center them
mfraw_eng$promdom.eff <- mfraw_eng$prom.eff - mfraw_eng$prev.eff
mfraw_eng$promdom.effc <- mfraw_eng$promdom.eff
mfraw_eng$promdom.effc <- as.numeric(scale(mfraw_eng$promdom.effc, center = TRUE, scale = FALSE))
mfraw_eng$locdom <- mfraw_eng$loc - mfraw_eng$ass
mfraw_eng$locdomc <- mfraw_eng$locdom
mfraw_eng$locdomc <- as.numeric(scale(mfraw_eng$locdomc, center = TRUE, scale = FALSE))

## MEMORY MEASURES (PREP)

# Dummy-code memory data (1 = remembered at all)
mfraw_eng$mem_scrutinize.d <- ifelse(is.na(mfraw_eng$mem_scrutinize), 0, 1)
mfraw_eng$mem_review.d <- ifelse(is.na(mfraw_eng$mem_review), 0, 1)
mfraw_eng$mem_judge.d <- ifelse(is.na(mfraw_eng$mem_judge), 0, 1)
mfraw_eng$mem_assess.d <- ifelse(is.na(mfraw_eng$mem_assess), 0, 1)
mfraw_eng$mem_examine.d <- ifelse(is.na(mfraw_eng$mem_examine), 0, 1)
mfraw_eng$mem_verify.d <- ifelse(is.na(mfraw_eng$mem_verify), 0, 1)
mfraw_eng$mem_explore.d <- ifelse(is.na(mfraw_eng$mem_explore), 0, 1)
mfraw_eng$mem_invent.d <- ifelse(is.na(mfraw_eng$mem_invent), 0, 1)
mfraw_eng$mem_seek.d <- ifelse(is.na(mfraw_eng$mem_seek), 0, 1)
mfraw_eng$mem_discover.d <- ifelse(is.na(mfraw_eng$mem_discover), 0, 1)
mfraw_eng$mem_imagine.d <- ifelse(is.na(mfraw_eng$mem_imagine), 0, 1)
mfraw_eng$mem_wonder.d <- ifelse(is.na(mfraw_eng$mem_wonder), 0, 1)
mfraw_eng$mem_guard.d <- ifelse(is.na(mfraw_eng$mem_guard), 0, 1)
mfraw_eng$mem_resist.d <- ifelse(is.na(mfraw_eng$mem_resist), 0, 1)
mfraw_eng$mem_defend.d <- ifelse(is.na(mfraw_eng$mem_defend), 0, 1)
mfraw_eng$mem_protect.d <- ifelse(is.na(mfraw_eng$mem_protect), 0, 1)
mfraw_eng$mem_preserve.d <- ifelse(is.na(mfraw_eng$mem_preserve), 0, 1)
mfraw_eng$mem_maintain.d <- ifelse(is.na(mfraw_eng$mem_maintain), 0, 1)
mfraw_eng$mem_propel.d <- ifelse(is.na(mfraw_eng$mem_propel), 0, 1)
mfraw_eng$mem_accelerate.d <- ifelse(is.na(mfraw_eng$mem_accelerate), 0, 1)
mfraw_eng$mem_progress.d <- ifelse(is.na(mfraw_eng$mem_progress), 0, 1)
mfraw_eng$mem_elevate.d <- ifelse(is.na(mfraw_eng$mem_elevate), 0, 1)
mfraw_eng$mem_lead.d <- ifelse(is.na(mfraw_eng$mem_lead), 0, 1)
mfraw_eng$mem_launch.d <- ifelse(is.na(mfraw_eng$mem_launch), 0, 1)
mfraw_eng$mem_control.d <- ifelse(is.na(mfraw_eng$mem_control), 0, 1)
mfraw_eng$mem_manage.d <- ifelse(is.na(mfraw_eng$mem_manage), 0, 1)
mfraw_eng$mem_operate.d <- ifelse(is.na(mfraw_eng$mem_operate), 0, 1)
mfraw_eng$mem_inquire.d <- ifelse(is.na(mfraw_eng$mem_inquire), 0, 1)
mfraw_eng$mem_investigate.d <- ifelse(is.na(mfraw_eng$mem_investigate), 0, 1)
mfraw_eng$mem_consider.d <- ifelse(is.na(mfraw_eng$mem_consider), 0, 1)
mfraw_eng$mem_communicate.d <- ifelse(is.na(mfraw_eng$mem_communicate), 0, 1)
mfraw_eng$mem_sleep.d <- ifelse(is.na(mfraw_eng$mem_sleep), 0, 1)
mfraw_eng$mem_shower.d <- ifelse(is.na(mfraw_eng$mem_shower), 0, 1)
mfraw_eng$mem_achieve.d <- ifelse(is.na(mfraw_eng$mem_achieve), 0, 1)
mfraw_eng$mem_gain.d <- ifelse(is.na(mfraw_eng$mem_gain), 0, 1)
mfraw_eng$mem_grow.d <- ifelse(is.na(mfraw_eng$mem_grow), 0, 1)
mfraw_eng$mem_prevent.d <- ifelse(is.na(mfraw_eng$mem_prevent), 0, 1)
mfraw_eng$mem_evade.d <- ifelse(is.na(mfraw_eng$mem_evade), 0, 1)
mfraw_eng$mem_secure.d <- ifelse(is.na(mfraw_eng$mem_secure), 0, 1)

# Gather memory rank data (from wide to long)
mfmem <- dplyr::select(mfraw_eng, "id", "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch", "mem_control", "mem_manage", "mem_operate", "mem_inquire", "mem_investigate", "mem_consider", "mem_communicate", "mem_sleep", "mem_shower", "mem_achieve", "mem_gain", "mem_grow", "mem_prevent", "mem_evade", "mem_secure")
mfmem <- gather(mfmem, key = stim, value = memrank, "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch", "mem_control", "mem_manage", "mem_operate", "mem_inquire", "mem_investigate", "mem_consider", "mem_communicate", "mem_sleep", "mem_shower", "mem_achieve", "mem_gain", "mem_grow", "mem_prevent", "mem_evade", "mem_secure")
mfmem$stim <- str_replace_all(mfmem$stim, fixed("mem_"), "")
mfmem$logmemrank <- log(mfmem$memrank) # Log-transform memrank so more normal
mfmem$memrank <- mfmem$memrank * -1 # reverse-score so higher = stronger
mfmem$logmemrank <- mfmem$logmemrank * -1 # reverse-score so higher = stronger

# Gather memory data (from wide to long)
mfmem.d <- dplyr::select(mfraw_eng, "id", "mem_scrutinize.d", "mem_review.d", "mem_judge.d", "mem_assess.d", "mem_examine.d", "mem_verify.d", "mem_explore.d", "mem_invent.d", "mem_seek.d", "mem_discover.d", "mem_imagine.d", "mem_wonder.d", "mem_guard.d", "mem_resist.d", "mem_defend.d", "mem_protect.d", "mem_preserve.d", "mem_maintain.d", "mem_propel.d", "mem_accelerate.d", "mem_progress.d", "mem_elevate.d", "mem_lead.d", "mem_launch.d", "mem_control.d", "mem_manage.d", "mem_operate.d", "mem_inquire.d", "mem_investigate.d", "mem_consider.d", "mem_communicate.d", "mem_sleep.d", "mem_shower.d", "mem_achieve.d", "mem_gain.d", "mem_grow.d", "mem_prevent.d", "mem_evade.d", "mem_secure.d")
mfmem.d <- gather(mfmem.d, key = stim, value = mem.d, "mem_scrutinize.d", "mem_review.d", "mem_judge.d", "mem_assess.d", "mem_examine.d", "mem_verify.d", "mem_explore.d", "mem_invent.d", "mem_seek.d", "mem_discover.d", "mem_imagine.d", "mem_wonder.d", "mem_guard.d", "mem_resist.d", "mem_defend.d", "mem_protect.d", "mem_preserve.d", "mem_maintain.d", "mem_propel.d", "mem_accelerate.d", "mem_progress.d", "mem_elevate.d", "mem_lead.d", "mem_launch.d", "mem_control.d", "mem_manage.d", "mem_operate.d", "mem_inquire.d", "mem_investigate.d", "mem_consider.d", "mem_communicate.d", "mem_sleep.d", "mem_shower.d", "mem_achieve.d", "mem_gain.d", "mem_grow.d", "mem_prevent.d", "mem_evade.d", "mem_secure.d")
mfmem.d$stim <- str_replace_all(mfmem.d$stim, fixed("mem_"), "")
mfmem.d$stim <- str_replace_all(mfmem.d$stim, fixed(".d"), "")

# Merge into a single mf dataframe
mf_eng <- merge(mfmem, mfraw_eng, all.x = T)
mf_eng <- merge(mf_eng, mfmem.d, all.x = T)

# Remove dataframes not needed further
rm(mfmem)
rm(mfmem.d)

# Reorder stimtype levels in stimlist
stimlist$stimtype.ord <- factor(stimlist$stimtype, ordered = TRUE, levels = c("tgen", "prevtruth", "promtruth", "cgen", "prevcontrol", "promcontrol", "gen"))
stimlist$stimrf.ord <- factor(stimlist$stimrf, ordered = TRUE, levels = c("prev", "prom", "gen"))
stimlist$stimtc.ord <- factor(stimlist$stimtc, ordered = TRUE, levels = c("truth", "control", "gen"))

# Merge mf_eng with stimlist
mf_eng <- merge(mf_eng, stimlist, all.x = T, by = "stim")

# Within-person memtotal
mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal = sum(mem.d)) %>%
  ungroup()

# Within-person motive-specific memtotal
mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_mot = sum(mem.d[stimtype == "prevtruth" | stimtype == "promtruth" | stimtype == "prevcontrol" | stimtype == "promcontrol"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_prevtruth = sum(mem.d[stimtype == "prevtruth"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_promtruth = sum(mem.d[stimtype == "promtruth"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_prevctrl = sum(mem.d[stimtype == "prevcontrol"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_promctrl = sum(mem.d[stimtype == "promcontrol"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_truth = sum(mem.d[stimtype == "prevtruth" | stimtype == "promtruth"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_ctrl = sum(mem.d[stimtype == "prevcontrol" | stimtype == "promcontrol"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_prom = sum(mem.d[stimtype == "promcontrol" | stimtype == "promtruth"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_prev = sum(mem.d[stimtype == "prevcontrol" | stimtype == "prevtruth"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_tgen = sum(mem.d[stimtype == "tgen"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_cgen = sum(mem.d[stimtype == "cgen"])) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memtotal_gen = sum(mem.d[stimtype == "gen"])) %>%
  ungroup()

memtotals <- unique(dplyr::select(mf_eng, id, memtotal, memtotal_mot, memtotal_prevtruth, memtotal_promtruth, memtotal_promctrl, memtotal_prevctrl, memtotal_truth, memtotal_ctrl, memtotal_prom, memtotal_prev, memtotal_tgen, memtotal_cgen, memtotal_gen))

mfraw_eng <- merge(mfraw_eng, memtotals)
rm(memtotals)

# Within-person relative motive importance (higher = stronger) based on proportion of total motive words remembered
mf_eng$prevtruth.memtotalprop.within <- mf_eng$memtotal_prevtruth / mf_eng$memtotal_mot
mf_eng$promtruth.memtotalprop.within <- mf_eng$memtotal_promtruth / mf_eng$memtotal_mot
mf_eng$prevctrl.memtotalprop.within <- mf_eng$memtotal_prevctrl / mf_eng$memtotal_mot
mf_eng$promctrl.memtotalprop.within <- mf_eng$memtotal_promctrl / mf_eng$memtotal_mot
mf_eng$tgen.memtotalprop.within <- mf_eng$memtotal_tgen / mf_eng$memtotal_mot
mf_eng$cgen.memtotalprop.within <- mf_eng$memtotal_cgen / mf_eng$memtotal_mot
mf_eng$truth.memtotalprop.within <- mf_eng$memtotal_truth / mf_eng$memtotal_mot
mf_eng$ctrl.memtotalprop.within <- mf_eng$memtotal_ctrl / mf_eng$memtotal_mot
mf_eng$prom.memtotalprop.within <- mf_eng$memtotal_prom / mf_eng$memtotal_mot
mf_eng$prev.memtotalprop.within <- mf_eng$memtotal_prev / mf_eng$memtotal_mot

mf_eng$prevtruth.memtotalprop <- mf_eng$memtotal_prevtruth / 6
mf_eng$promtruth.memtotalprop <- mf_eng$memtotal_promtruth / 6
mf_eng$prevctrl.memtotalprop <- mf_eng$memtotal_prevctrl / 6
mf_eng$promctrl.memtotalprop <- mf_eng$memtotal_promctrl / 6
mf_eng$tgen.memtotalprop <- mf_eng$memtotal_tgen / 3
mf_eng$cgen.memtotalprop <- mf_eng$memtotal_cgen / 3
mf_eng$truth.memtotalprop <- mf_eng$memtotal_truth / 12
mf_eng$ctrl.memtotalprop <- mf_eng$memtotal_ctrl / 12
mf_eng$prom.memtotalprop <- mf_eng$memtotal_prom / 12
mf_eng$prev.memtotalprop <- mf_eng$memtotal_prev /12

memtotalprops <- unique(dplyr::select(mf_eng, id, prevtruth.memtotalprop.within, promtruth.memtotalprop.within, prevctrl.memtotalprop.within, promctrl.memtotalprop.within, tgen.memtotalprop.within, cgen.memtotalprop.within, truth.memtotalprop.within, ctrl.memtotalprop.within, prom.memtotalprop.within, prev.memtotalprop.within, prevtruth.memtotalprop, promtruth.memtotalprop, prevctrl.memtotalprop, promctrl.memtotalprop, tgen.memtotalprop, cgen.memtotalprop, truth.memtotalprop, ctrl.memtotalprop, prom.memtotalprop, prev.memtotalprop))

mfraw_eng <- merge(mfraw_eng, memtotalprops)
rm(memtotalprops)

# Within-person motive-specific memrank
mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_mot = mean(memrank[stimtype == "prevtruth" | stimtype == "promtruth" | stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_prevtruth = mean(memrank[stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_promtruth = mean(memrank[stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_prevctrl = mean(memrank[stimtype == "prevcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_promctrl = mean(memrank[stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_truth = mean(memrank[stimtype == "prevtruth" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_ctrl = mean(memrank[stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_prom = mean(memrank[stimtype == "promcontrol" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_prev = mean(memrank[stimtype == "prevcontrol" | stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_tgen = mean(memrank[stimtype == "tgen"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_cgen = mean(memrank[stimtype == "cgen"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(memrank_gen = mean(memrank[stimtype == "gen"], na.rm = TRUE)) %>%
  ungroup()

mf_eng$memrank_promdom <- mf_eng$memrank_prom - mf_eng$memrank_prev

memranks <- unique(dplyr::select(mf_eng, id, memrank_mot, memrank_prevtruth, memrank_promtruth, memrank_promctrl, memrank_prevctrl, memrank_truth, memrank_ctrl, memrank_prom, memrank_prev, memrank_tgen, memrank_cgen, memrank_gen, memrank_promdom))

mfraw_eng <- merge(mfraw_eng, memranks)
rm(memranks)

mfraw_eng$memrank_prom_all <- mfraw_eng$memrank_prom
mfraw_eng$memrank_prom_all <- ifelse(is.nan(mfraw_eng$memrank_prom), -1 * (mfraw_eng$memtotal + 1), mfraw_eng$memrank_prom)
mfraw_eng$memrank_prom_all <- ifelse(mfraw_eng$memrank_prom_all == 0, NA, mfraw_eng$memrank_prom_all)
mfraw_eng$logmemrank_prom_all <- -1 * log(-1 * mfraw_eng$memrank_prom_all)

mfraw_eng$memrank_prev_all <- mfraw_eng$memrank_prev
mfraw_eng$memrank_prev_all <- ifelse(is.nan(mfraw_eng$memrank_prev), -1 * (mfraw_eng$memtotal + 1), mfraw_eng$memrank_prev)
mfraw_eng$memrank_prev_all <- ifelse(mfraw_eng$memrank_prev_all == 0, NA, mfraw_eng$memrank_prev_all)
mfraw_eng$logmemrank_prev_all <- -1 * log(-1 * mfraw_eng$memrank_prev_all)

mfraw_eng$memrank_all_promdom <- mfraw_eng$memrank_prom_all - mfraw_eng$memrank_prev_all
mfraw_eng$logmemrank_all_promdom <- mfraw_eng$logmemrank_prom_all - mfraw_eng$logmemrank_prev_all

# Within-person motive-specific logmemrank
mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_mot = mean(logmemrank[stimtype == "prevtruth" | stimtype == "promtruth" | stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_prevtruth = mean(logmemrank[stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_promtruth = mean(logmemrank[stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_prevctrl = mean(logmemrank[stimtype == "prevcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_promctrl = mean(logmemrank[stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_truth = mean(logmemrank[stimtype == "prevtruth" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_ctrl = mean(logmemrank[stimtype == "prevcontrol" | stimtype == "promcontrol"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_prom = mean(logmemrank[stimtype == "promcontrol" | stimtype == "promtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_prev = mean(logmemrank[stimtype == "prevcontrol" | stimtype == "prevtruth"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_tgen = mean(logmemrank[stimtype == "tgen"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_cgen = mean(logmemrank[stimtype == "cgen"], na.rm = TRUE)) %>%
  ungroup()

mf_eng <- mf_eng %>%
  group_by(id) %>%
  mutate(logmemrank_gen = mean(logmemrank[stimtype == "gen"], na.rm = TRUE)) %>%
  ungroup()

mf_eng$logmemrank_promdom <- mf_eng$logmemrank_prom - mf_eng$logmemrank_prev

logmemranks <- unique(dplyr::select(mf_eng, id, logmemrank_mot, logmemrank_prevtruth, logmemrank_promtruth, logmemrank_promctrl, logmemrank_prevctrl, logmemrank_truth, logmemrank_ctrl, logmemrank_prom, logmemrank_prev, logmemrank_tgen, logmemrank_cgen, logmemrank_gen, logmemrank_promdom))

mfraw_eng <- merge(mfraw_eng, logmemranks)
rm(logmemranks)

# Determinining which stimtype was remembered first, and then dummy-coding and merging
memrankfirst <- mfraw_eng %>%
  group_by(id) %>%
  gather(key = "memrank_first_stim", value = "memrank_first_stimrank", "mem_scrutinize", "mem_review", "mem_judge", "mem_assess", "mem_examine", "mem_verify", "mem_explore", "mem_invent", "mem_seek", "mem_discover", "mem_imagine", "mem_wonder", "mem_guard", "mem_resist", "mem_defend", "mem_protect", "mem_preserve", "mem_maintain", "mem_propel", "mem_accelerate", "mem_progress", "mem_elevate", "mem_lead", "mem_launch")
memrankfirst$memrank_first_stim <- str_replace_all(memrankfirst$memrank_first_stim, fixed("mem_"), "")
memrankfirst <- dplyr::select(memrankfirst, id, memrank_first_stim, memrank_first_stimrank)
memrankfirst <- na.omit(memrankfirst, cols = "memrank_first_stimrank")
memrankfirst <- memrankfirst %>%
  group_by(id) %>%
  mutate(minmemrank_rmf = min(memrank_first_stimrank, na.rm = TRUE)) %>%
  mutate(firststim = memrank_first_stim[memrank_first_stimrank == minmemrank_rmf])

# Breaking out a separate dataframe to determine ranks of first promotion and prevention
memrankfirst_prom <- merge(memrankfirst, stimlist, by.x = "memrank_first_stim", by.y = "stim")
memrankfirst_prom <- memrankfirst_prom %>%
  group_by(id) %>%
  filter(stimrf == "prom") %>%
  mutate(minmemrank_prom = min(memrank_first_stimrank, na.rm = TRUE)) %>%
  mutate(firststim_prom = memrank_first_stim[memrank_first_stimrank == minmemrank_prom])

memrankfirst_prev <- merge(memrankfirst, stimlist, by.x = "memrank_first_stim", by.y = "stim")
memrankfirst_prev <- memrankfirst_prev %>%
  group_by(id) %>%
  filter(stimrf == "prev") %>%
  mutate(minmemrank_prev = min(memrank_first_stimrank, na.rm = TRUE)) %>%
  mutate(firststim_prev = memrank_first_stim[memrank_first_stimrank == minmemrank_prev])

memrankfirst$memrank_first_stim <- NULL
memrankfirst$minmemrank_rmf <- NULL
memrankfirst$memrank_first_stimrank <- NULL
memrankfirst <- distinct(memrankfirst)
memrankfirst <- memrankfirst %>%
  rename(stim = firststim)
memrankfirst <- merge(memrankfirst, stimlist, by = "stim")
memrankfirst$stimnum <- NULL
memrankfirst$freq <- NULL
memrankfirst$length <- NULL
memrankfirst$freq.s <- NULL
memrankfirst$length.s <- NULL
memrankfirst$stimtc_pred <- NULL
memrankfirst$stimrf_pred <- NULL
memrankfirst$stimtc.ord <- NULL
memrankfirst$stimrf.ord <- NULL
memrankfirst <- memrankfirst %>%
  rename(memfirst_stim = stim, memfirst_rf = stimrf, memfirst_tc = stimtc, memfirst_stimtype = stimtype, memfirst_stimtype_ord = stimtype.ord, )
memrankfirst$memfirst_rf.e <- 0
memrankfirst$memfirst_rf.e[memrankfirst$memfirst_rf == "prom"] <- .5
memrankfirst$memfirst_rf.e[memrankfirst$memfirst_rf == "prev"] <- -.5
memrankfirst$memfirst_rf.d <- 0
memrankfirst$memfirst_rf.d[memrankfirst$memfirst_rf == "prom"] <- 1
memrankfirst$memfirst_rf.d[memrankfirst$memfirst_rf == "prev"] <- 0
memrankfirst$memfirst_tc.e <- 0
memrankfirst$memfirst_tc.e[memrankfirst$memfirst_tc == "control"] <- .5
memrankfirst$memfirst_tc.e[memrankfirst$memfirst_tc == "truth"] <- -.5
memrankfirst$memfirst_tc.d <- 0
memrankfirst$memfirst_tc.d[memrankfirst$memfirst_tc == "control"] <- 1
memrankfirst$memfirst_tc.d[memrankfirst$memfirst_tc == "truth"] <- 0
mfraw_eng <- merge(mfraw_eng, memrankfirst, by = "id", all = TRUE)
rm(memrankfirst)

memrankfirst_prom$memrank_first_stim <- NULL
memrankfirst_prom$minmemrank_rmf <- NULL
memrankfirst_prom$memrank_first_stimrank <- NULL
memrankfirst_prom$firststim <- NULL
memrankfirst_prom$stimnum <- NULL
memrankfirst_prom$stimtype <- NULL
memrankfirst_prom$stimtc <- NULL
memrankfirst_prom$stimrf <- NULL
memrankfirst_prom$freq <- NULL
memrankfirst_prom$length <- NULL
memrankfirst_prom$stimtype.ord <- NULL
memrankfirst_prom$stimtc_pred <- NULL
memrankfirst_prom$stimrf_pred <- NULL
memrankfirst_prom$stimtc.ord <- NULL
memrankfirst_prom$stimrf.ord <- NULL
memrankfirst_prom <- distinct(memrankfirst_prom)
memrankfirst_prom <- memrankfirst_prom %>% 
  slice(1) %>% # takes the first occurrence if there is a tie
  ungroup()
mfraw_eng <- merge(mfraw_eng, memrankfirst_prom, by = "id", all.x = TRUE)
mf_eng <- merge(mf_eng, memrankfirst_prom, by = "id", all.x = TRUE)
rm(memrankfirst_prom)

memrankfirst_prev$memrank_first_stim <- NULL
memrankfirst_prev$minmemrank_rmf <- NULL
memrankfirst_prev$memrank_first_stimrank <- NULL
memrankfirst_prev$firststim <- NULL
memrankfirst_prev$stimnum <- NULL
memrankfirst_prev$stimtype <- NULL
memrankfirst_prev$stimtc <- NULL
memrankfirst_prev$stimrf <- NULL
memrankfirst_prev$freq <- NULL
memrankfirst_prev$length <- NULL
memrankfirst_prev$stimtype.ord <- NULL
memrankfirst_prev$stimtc_pred <- NULL
memrankfirst_prev$stimrf_pred <- NULL
memrankfirst_prev$stimtc.ord <- NULL
memrankfirst_prev$stimrf.ord <- NULL
memrankfirst_prev <- distinct(memrankfirst_prev)
memrankfirst_prev <- memrankfirst_prev %>% 
  slice(1) %>% # takes the first occurrence if there is a tie
  ungroup()
mfraw_eng <- merge(mfraw_eng, memrankfirst_prev, by = "id", all.x = TRUE)
mf_eng <- merge(mf_eng, memrankfirst_prev, by = "id", all.x = TRUE)
rm(memrankfirst_prev)

mfraw_eng$minmemrank_prom <- mfraw_eng$minmemrank_prom * -1 # So higher = stronger
mfraw_eng$minmemrank_prev <- mfraw_eng$minmemrank_prev * -1 # So higher = stronger
mfraw_eng$minmemrank_promdom <- mfraw_eng$minmemrank_prom - mfraw_eng$minmemrank_prev

mfraw_eng$memfirst_stimtype_ord <- factor(mfraw_eng$memfirst_stimtype_ord, ordered = TRUE, levels = c("prevtruth", "promtruth", "prevcontrol", "promcontrol"))

# Mean-centering predictors of interest
mf_eng$length <- nchar(as.character(mf_eng$stim))
mf_eng$length.s <- as.numeric(scale(mf_eng$length))
mf_eng$freq.s <- as.numeric(scale(mf_eng$freq))
mf_eng$stimrf.e <- 0
mf_eng$stimrf.e[mf_eng$stimrf == "prom"] <- .5
mf_eng$stimrf.e[mf_eng$stimrf == "prev"] <- -.5
mf_eng$stimtc.e <- 0
mf_eng$stimtc.e[mf_eng$stimtc == "control"] <- .5
mf_eng$stimtc.e[mf_eng$stimtc == "truth"] <- -.5
mf$memtotal.s <- as.numeric(scale(mf$memtotal))
mf$memtotal_process.s <- as.numeric(scale(mf$memtotal_process))
```

# Save Cleaned Original Dataset

```{r save}
# SAVING CLEAN DATASETS
save(mfraw, mf, improper_rfind, nonenglish, nonenglishpct, mfraw_eng, mf_eng, file = "data/RFgoalpursuit_study2b_clean.RData")
```

# De-Identify Cleaned Dataset

```{r deidentify}
# REMOVE IP ADDRESSES AND LATITUDE/LONGITUDE FROM ALL DATAFRAMES SO THESE DE-IDENTIFIED DATA CAN BE PUBLICLY SHARED
mfraw$IPAddress <- NULL
mf$IPAddress <- NULL
mfraw$LocationLatitude <- NULL
mf$LocationLatitude <- NULL
mfraw$LocationLongitude <- NULL
mf$LocationLongitude <- NULL

mfraw_eng$IPAddress <- NULL
mf_eng$IPAddress <- NULL
mfraw_eng$LocationLatitude <- NULL
mf_eng$LocationLatitude <- NULL
mfraw_eng$LocationLongitude <- NULL
mf_eng$LocationLongitude <- NULL
```

# Save Cleaned and De-Identified Dataset

```{r save_deidentified}
# SAVING CLEAN DATASETS
save(mfraw, mf, improper_rfind, nonenglish, nonenglishpct, mfraw_eng, mf_eng, file = "data/RFgoalpursuit_study2b_clean_deidentified.RData")
```
